apiVersion: v1
kind: Service
metadata:
  name: api-bridge
spec:
  selector:
    app: api-bridge
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: node
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-bridge
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: api-bridge
        tier: backend
        track: stable
    spec:     # pod spec
      containers:
      - name: api-bridge
        ports:
        - name: node
          containerPort: 3000
        image: us.gcr.io/lifeid-dev/api-bridge:1.0.11 # image we pushed
