apiVersion: v1
kind: Service
metadata:
  name: claim-issuer
spec:
  selector:
    app: claim-issuer
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: node
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: claim-issuer
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: claim-issuer
        tier: backend
        track: stable
    spec:     # pod spec
      containers:
      - name: claim-issuer
        ports:
        - name: node
          containerPort: 3000
        image: us.gcr.io/lifeid-dev/claim-issuer:1.0.7
        env:
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: claim-issuer-config
                key: redisUrl
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: claim-issuer-config
                key: host
          - name: PRIVATE_KEY
            valueFrom:
              configMapKeyRef:
                name: claim-issuer-config
                key: privateKey

